### ISSUE TITLE
Crida al getEntityInside (per entrar als bunkers)

### ISSUE THREAD

**Issue by AleixBV** [crandino/StarCraft#13]
tal com està fet un cop has clicat per a que entrin en un bunker llavors només es necessari que finalitzin qualsevol path que se'ls hi doni per entrar. Per tant si agafes marines, cliques al bunker per a que entrin i llavors cliques per a que vagin a un altre lloc, quan hi arribin entraran al bunker independentment de la distància a la que estiguin

**Comment by AleixBV** [comment]
@N4bi Crec que ho he arreglat, per si vols testejar i tancar-ho

**Comment by N4bi** [comment]
En efecto, esta arreglado ;)
