### ISSUE TITLE
treure unitats dels bunkers

### ISSUE THREAD

**Issue by AleixBV** [crandino/StarCraft#14]
actualment al tenir solament un punter des del gui i actualitzar-lo quan cliques amb unitats al bunker, si fiques unitats dins de dos bunkers només podràs treure les del primer bunker amb el botó.

**Comment by AleixBV** [comment]
@N4bi Ho he arreglat, he provat i sembla que ja està correcte :)

**Comment by N4bi** [comment]
Testeado y funcionando correctamente, cierro issue
