### ISSUE TITLE
Si els Marines es moren mentre s'estan movent no desapareixen. 

### ISSUE THREAD

**Issue by mickifricki** [crandino/StarCraft#15]
Si es seleccionen uns quants Marines i es comencen a moure d'un costat a un altre mentre els zergs els ataquen, els Marines moren però no desapareixen. Això vol dir que la seva barra de vida desapareix i els zergs deixen d'atacar-los, però el Marine segueix en el joc i pot continuar disparant.

**Comment by AleixBV** [comment]
@N4bi Crec que ho he arreglat

**Comment by N4bi** [comment]
en principio esta arreglado, cierro issue
