### ISSUE TITLE
Firebat attack bug

### ISSUE THREAD

**Issue by weprikjm** [crandino/StarCraft#18]
If a firebat is attacking when jim raynor dies and the game ends. When you restart the game the particles being shot from the firebat are infinitely being shot.

**Comment by N4bi** [comment]
Bug apparently solved, closing issue

**Comment by N4bi** [comment]
With the fix, should be solved, but in one try with more than 2 firebats, the particle of the third firebat stayed in the next game... 1 of 20 times. I let the issue open and we will see another solution

**Comment by N4bi** [comment]
He hecho un nuevo fix y parece que no ya no se da el problema, cierro issue
