### ISSUE TITLE
Tanks: Falta la gui pels tancs

### ISSUE THREAD

**Issue by AleixBV** [crandino/StarCraft#22]
actualment el siege_mode s'activa o desactiva apretant la "q" o la "a" respectivament, pero activa tots els tancs indiferentment de que estiguin seleccionats o no. S'hauria de fer la seva gui i que només se mostrés si tens unicament un tanc seleccionat.

**Comment by N4bi** [comment]
Ya se ha implementado el siege mode de los tanques en la UI, cierro
