### ISSUE TITLE
Entity Manager: Opcion para deshacer la construccion de edificio 

### ISSUE THREAD

**Issue by N4bi** [crandino/StarCraft#3]
Cuando seleccionas una construcción y ya la tienes para montarla, debería poderse cancelar con el botón derecho del ratón, desactivando así el building mode. Actualmente, si te arrepientes de seleccionar esa construcción no hay posibilidad alguna de cancelar. Cuando se cancele el building mode en este caso se te debería devolver los recursos empleados.

**Comment by AleixBV** [comment]
Ara amb el botó dret del ratolí canceles la construcció, fa el mateix que quan guanyes o perds, i com que actualment només et resta els recursos quan col·loques la construcció, no te'ls arriba a restar.
