### ISSUE TITLE
Problema con respawn de unidades enemigas 

### ISSUE THREAD

**Issue by N4bi** [crandino/StarCraft#41]
A partir de la oleada 19 (cuando el numero de enemigos es muy grande), si la oleada biene de la parte de arriba a la derecha, algunos enemigos se quedan enganchados porque hacen el respawn en un area no walkable. Hasta que no los matas el ciclo de juego no continua y no pasas a la siguiente oleada.

Adjunto screenshot del punto donde se quedan las unidades 

![captura](https://cloud.githubusercontent.com/assets/10940471/15178438/da31147a-1775-11e6-94ce-61daeb696a67.PNG)

**Comment by AleixBV** [comment]
He fet que si apareixen en tiles no walkables se moguin, així tant si hi construeixes com si passes a rondes molt avançades en cap cas pugui succeïr aquest issue.
