### ISSUE TITLE
Si els tanks moren quan estan plantats el terra no torna a ser walkable.

### ISSUE THREAD

**Issue by mickifricki** [crandino/StarCraft#50]
- Frequency: Sempre
- Steps to reproduce:
- Result:
- Expected result:

**Comment by N4bi** [comment]
- Frequency: 100%
- Steps to reproduce:
  - put tanks in siege mode
  - let tanks die
- Result: Ground where the tanks were is no walkable
- Expected result: When the tank dies, the ground should be walkable again

**Comment by AleixBV** [comment]
Qui va fer el mètode deletionManager que torni a ficar lo que hi havia abans al preUpdate...

**Comment by AleixBV** [comment]
Osigui em refereixo a que si ho ha tret del preUpdate per a fer el mètode que hi fiqui tot el que hi havia...

**Comment by N4bi** [comment]
Se cierra porque los tanques ya no cambian la logica del suelo, asi que esto ya no es un problema
