### ISSUE TITLE
Focus Attack no funciona como debe 

### ISSUE THREAD

**Issue by N4bi** [crandino/StarCraft#52]
- Frequency: 100%
- Steps to reproduce:
  - coger un grupo elevado de unidades ( aprox. 20 o mas  )
  - clickar sobre un enemigo ( preferiblemente hydralisko o ultralisko )
- Result: No todas las unidades seleccionadas van a atacar al objetivo, además las unidades que van a atacar se ponen a melee del objetivo cuando podrían atacar desde una posición mas lejana.
- Expected result: Todas las unidades deberían moverse hasta tener rango de ataque y atacar al objetivo que se ha clickado.

**Comment by AleixBV** [comment]
ja ho vaig arreglar fa un temps, proveu a veure si funciona com hauria, no m'ha passat més.

**Comment by N4bi** [comment]
En principio parece que funciona bien por lo que he probado, cierro issue
