### ISSUE TITLE
GUI: Información de recursos de las unidades

### ISSUE THREAD

**Issue by crandino** [crandino/StarCraft#57]
- Frequency: 100%
- Steps to reproduce: Si tenemos el ratón sobre la creación de alguna unidad y nos destruyen barraca o fábrica, el letrero informativo sobre su coste permanecerá hasta que empiece de nuevo la partida.
- Result:
- Expected result: Debería desaparecer si desaparece el edificio que lo ha generado

**Comment by N4bi** [comment]
fixed
