### ISSUE TITLE
Bunker doesn't attack close combat units

### ISSUE THREAD

**Issue by weprikjm** [crandino/StarCraft#58]
- Frequency: 100%
- Steps to reproduce: Si poses una unitat enemiga just davant d'un bunker el bunker para l'animació i deixa de produïr dany al cap de 2 segons que la unitat enemiga comenci a atacar (cos a cos: zergling, ultralisk)
- Result: el bunker deixa de disparar i no fa mal a les unitats cos a cos
- Expected result: el bunker hauria d'atacar a les unitats que ataquen cos a cos

**Comment by AleixBV** [comment]
La qüestió era que creaves els enemics a sobre del bunker de manera que els colliders es sobreposaven, ja està solucionat.
