### ISSUE TITLE
Crash al cargar partida interaccionando con bunkers

### ISSUE THREAD

**Issue by N4bi** [crandino/StarCraft#65]
- Frequency:100%
- Steps to reproduce:
  1. Meter un firebat en el bunker
  2. Guardar partida con F5
  3. Sacar al firebat del bunker
  4. Cargar partida con F6
  5. Darle al boton de vaciar el bunker
- Result: El juego se congela, no sale ni breakpoint ni nada, simplemente se queda congelado. 
- Expected result: Una vez cargada la partida el firebat pudiera salir del bunker y la partida continue normalmente

**Comment by N4bi** [comment]
He hecho el pausa como me dijo Carlos y parece ser que se queda en un bucle de la funcion find del pathfinding, adjunto screenshot
![issue](https://cloud.githubusercontent.com/assets/10940471/15630494/15ff6922-253e-11e6-934b-395153aee99d.PNG)

**Comment by crandino** [comment]
Tile_pos is saved too.
