### ISSUE TITLE
Sprite hud terran está defectuoso

### ISSUE THREAD

**Issue by N4bi** [crandino/StarCraft#66]
- Frequency: 100%
- Steps to reproduce:
- Result: En el lugar donde van los portraits, hay un agujero en el cual se puede ver lo que hay debajo. Adjunto imagen
- Expected result:
- Screenshot del error
  ![issue](https://cloud.githubusercontent.com/assets/10940471/15622062/d4fe250e-2465-11e6-90cb-09021b213ff0.PNG)

**Comment by crandino** [comment]
Iván tells me that it is solved
