### ISSUE TITLE
Problema amb búnkers al ser destruits

### ISSUE THREAD

**Issue by mickifricki** [crandino/StarCraft#68]
- Frequency: 100%
- Steps to reproduce: 
  -Crear un búnker
  -Enviar unitats cap a dins el búnker
  -Destruir el búnker abans no arribin les unitats
- Result: El joc peta. 
- Expected result: El joc no hauria de petar.

**Comment by N4bi** [comment]
No consigo reproducirlo, los pasos que he seguido han sido
- Ejecutar el juego
- Modo debug
- Darle a la R para subir los recursos
- colocar un bunker desde el command center
- meter los dos marines + raynor en el bunker
- darle al KP9 para sacar ultraliskos
- el bunker se destruye y las unidades salen normalmente

Todo ello lo he hecho antes de que llegue la wave 1

**Comment by mickifricki** [comment]
Lo has hecho mal. Tienes que enviar las unidades hacia el búnker, pero tienes que destruirlo antes de que lleguen a entrar, es entonces cuando peta.

**Comment by N4bi** [comment]
Vale, es justo antes de que las unidades que has mandado al bunker entren a el. Me habia confundido con la llegada de oleadas enemigas, peta en el Tree porque se quedan sin el objetivo para entrar.

**Comment by N4bi** [comment]
Cambio label porque las circunstancias que se tienen que dar para que eso ocurra, en una partida normal son bastante dificiles, porque cuando te destruyen el bunker y tu clickas con las unidades hacia ese bunker, ellos van pero si se encuentran por el camino con el enemigo que ha destruido ese bunker(que suele ser lo mas normal) se paran y atacan con lo que no llega a reproducirse el bug. Se queda abierto, pero no es critico, porque en situación de juego normal es bastante complicado que ocurra.
