### ISSUE TITLE
Bunker error: units getting out of the bunker.

### ISSUE THREAD

**Issue by weprikjm** [crandino/StarCraft#70]
- Frequency: 100%
- Steps to reproduce: Save the game in phase 2 with bunkers with units inside then load the game. 
- Result: When you load the game in the phase 2 and there are more than 1 entities inside a bunker and you let them out the game gets stuck inside a while loop in findNearestAdjacentTile
- Expected result: The units should come out of the bunker normally

**Comment by crandino** [comment]
This bug was duplicated. It's solved.
